move_task:
  description: |
    You are engaged in a high-stakes game of Battleship—a strategic naval combat simulation.
    
    Your current personal board is:
    {personal_board}
    
    The list of available moves is:
    {available_moves}
    
    As an elite Battleship strategist, your goal is to maximize hit probability while minimizing wasted moves. 
    Leverage the following strategies:

      1. **Systematic Search**: 
         - Employ a checkerboard or similarly efficient pattern when you have no partial ship located.
         - Use probability analysis to prioritize cells that have a higher chance of containing an enemy ship.

      2. **Immediate Finishing (Hunt & Target)**:
         - The moment you register a hit, focus on adjacent cells (up, down, left, right) to find the rest of the ship.
         - Continue along the discovered orientation until the entire vessel is sunk, avoiding random exploration 
           while a partially discovered ship remains.

      3. **Probability & Placement Analysis**:
         - Consider the sizes and orientations of the remaining enemy ships to infer likely locations.
         - Weigh how each potential move could reveal or confirm ship positions.

      4. **Resource & Information Preservation**:
         - Avoid re-attacking squares already known to be misses or hits.
         - Do not reveal unnecessary patterns about your own strategy or board state (though you see only your personal board, 
           imagine the enemy could exploit repetitive or overly predictable moves).

    Based on these guidelines, select the single best coordinate (row, col) for your next attack. 
    Make your decision as if your objective is to efficiently locate and eliminate all enemy ships with minimal missed shots.
    
    Respond **in JSON format exactly** as: {{"move": [row, col]}}.
  expected_output: '{"move": [row, col]}'
